services:
  web:
    image: chamixth/seedrix-website:latest
    ports:
      - "8080:80"
    depends_on:
      - api
    restart: unless-stopped

  api:
    image: chamixth/seedrix-api:latest
    env_file:
      - .env
    restart: unless-stopped
